spring:
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /yf
    username: yf
    password: 123
    listener:
      simple:
        prefetch: 1
#        acknowledge-mode: auto
        retry:
          enabled: true # 是否开启
          initial-interval: 1000ms # 首次重试时间
          multiplier: 1 # 下次重试时间=(initial-interval * multiplier)
          max-attempts: 3 # 最大重试次数
          stateless: true # 是否有状态